mod arithmetic;
mod bit;
mod jump;
mod load;
mod misc;

use crate::memory_map::MemoryMap;
use crate::Cpu;

#[derive(Clone, Copy)]
pub struct Instruction {
    pub name: &'static str,
    pub length: u8,
    pub function: fn(&mut Cpu, &mut MemoryMap) -> u8,
}

impl Instruction {
    #[allow(dead_code)]
    pub const fn new(
        name: &'static str,
        length: u8,
        function: fn(&mut Cpu, &mut MemoryMap) -> u8,
    ) -> Self {
        Self {
            name,
            length,
            function,
        }
    }
}

#[allow(dead_code)]
fn undefined(_cpu: &mut Cpu, _memory_map: &mut MemoryMap) -> u8 {
    4
}

const UNDEFINED: Instruction = Instruction::new("UNDEFINED", 1, undefined);

pub const INSTRUCTIONS: [Instruction; 0x100] = [
    Instruction::new("NOP", 1, misc::nop),
    Instruction::new("LD BC,d16", 3, load::ld_bc_d16),
    Instruction::new("LD (BC),A", 1, load::ld_bc_addr_a),
    Instruction::new("INC BC", 1, arithmetic::inc_bc),
    Instruction::new("INC B", 1, arithmetic::inc_b),
    Instruction::new("DEC B", 1, arithmetic::dec_b),
    Instruction::new("LD B,d8", 2, load::ld_b_d8),
    Instruction::new("RLCA", 1, bit::rlca),
    Instruction::new("LD (a16),SP", 3, load::ld_a16_addr_sp),
    Instruction::new("ADD HL,BC", 1, arithmetic::add_hl_bc),
    Instruction::new("LD A,(BC)", 1, load::ld_a_bc_addr),
    Instruction::new("DEC BC", 1, arithmetic::dec_bc),
    Instruction::new("INC C", 1, arithmetic::inc_c),
    Instruction::new("DEC C", 1, arithmetic::dec_c),
    Instruction::new("LD C,d8", 2, load::ld_c_d8),
    Instruction::new("RRCA", 1, bit::rrca),
    Instruction::new("STOP 0", 1, misc::stop_0),
    Instruction::new("LD DE,d16", 3, load::ld_de_d16),
    Instruction::new("LD (DE),A", 1, load::ld_de_addr_a),
    Instruction::new("INC DE", 1, arithmetic::inc_de),
    Instruction::new("INC D", 1, arithmetic::inc_d),
    Instruction::new("DEC D", 1, arithmetic::dec_d),
    Instruction::new("LD D,d8", 2, load::ld_d_d8),
    Instruction::new("RLA", 1, bit::rla),
    Instruction::new("JR r8", 2, jump::jr_r8),
    Instruction::new("ADD HL,DE", 1, arithmetic::add_hl_de),
    Instruction::new("LD A,(DE)", 1, load::ld_a_de_addr),
    Instruction::new("DEC DE", 1, arithmetic::dec_de),
    Instruction::new("INC E", 1, arithmetic::inc_e),
    Instruction::new("DEC E", 1, arithmetic::dec_e),
    Instruction::new("LD E,d8", 2, load::ld_e_d8),
    Instruction::new("RRA", 1, bit::rra),
    Instruction::new("JR NZ,r8", 2, jump::jr_nz_r8),
    Instruction::new("LD HL,d16", 3, load::ld_hl_d16),
    Instruction::new("LD (HL+),A", 1, load::ld_hl_plus_addr_a),
    Instruction::new("INC HL", 1, arithmetic::inc_hl),
    Instruction::new("INC H", 1, arithmetic::inc_h),
    Instruction::new("DEC H", 1, arithmetic::dec_h),
    Instruction::new("LD H,d8", 2, load::ld_h_d8),
    Instruction::new("DAA", 1, arithmetic::daa),
    Instruction::new("JR Z,r8", 2, jump::jr_z_r8),
    Instruction::new("ADD HL,HL", 1, arithmetic::add_hl_hl),
    Instruction::new("LD A,(HL+)", 1, load::ld_a_hl_plus_addr),
    Instruction::new("DEC HL", 1, arithmetic::dec_hl),
    Instruction::new("INC L", 1, arithmetic::inc_l),
    Instruction::new("DEC L", 1, arithmetic::dec_l),
    Instruction::new("LD L,d8", 2, load::ld_l_d8),
    Instruction::new("CPL", 1, arithmetic::cpl),
    Instruction::new("JR NC,r8", 2, jump::jr_nc_r8),
    Instruction::new("LD SP,d16", 3, load::ld_sp_d16),
    Instruction::new("LD (HL-),A", 1, load::ld_hl_minus_addr_a),
    Instruction::new("INC SP", 1, arithmetic::inc_sp),
    Instruction::new("INC (HL)", 1, arithmetic::inc_hl_addr),
    Instruction::new("DEC (HL)", 1, arithmetic::dec_hl_addr),
    Instruction::new("LD (HL),d8", 2, load::ld_hl_addr_d8),
    Instruction::new("SCF", 1, arithmetic::scf),
    Instruction::new("JR C,r8", 2, jump::jr_c_r8),
    Instruction::new("ADD HL,SP", 1, arithmetic::add_hl_sp),
    Instruction::new("LD A,(HL-)", 1, load::ld_a_hl_minus_addr),
    Instruction::new("DEC SP", 1, arithmetic::dec_sp),
    Instruction::new("INC A", 1, arithmetic::inc_a),
    Instruction::new("DEC A", 1, arithmetic::dec_a),
    Instruction::new("LD A,d8", 2, load::ld_a_d8),
    Instruction::new("CCF", 1, arithmetic::ccf),
    Instruction::new("LD B,B", 1, load::ld_b_b),
    Instruction::new("LD B,C", 1, load::ld_b_c),
    Instruction::new("LD B,D", 1, load::ld_b_d),
    Instruction::new("LD B,E", 1, load::ld_b_e),
    Instruction::new("LD B,H", 1, load::ld_b_h),
    Instruction::new("LD B,L", 1, load::ld_b_l),
    Instruction::new("LD B,(HL)", 1, load::ld_b_hl_addr),
    Instruction::new("LD B,A", 1, load::ld_b_a),
    Instruction::new("LD C,B", 1, load::ld_c_b),
    Instruction::new("LD C,C", 1, load::ld_c_c),
    Instruction::new("LD C,D", 1, load::ld_c_d),
    Instruction::new("LD C,E", 1, load::ld_c_e),
    Instruction::new("LD C,H", 1, load::ld_c_h),
    Instruction::new("LD C,L", 1, load::ld_c_l),
    Instruction::new("LD C,(HL)", 1, load::ld_c_hl_addr),
    Instruction::new("LD C,A", 1, load::ld_c_a),
    Instruction::new("LD D,B", 1, load::ld_d_b),
    Instruction::new("LD D,C", 1, load::ld_d_c),
    Instruction::new("LD D,D", 1, load::ld_d_d),
    Instruction::new("LD D,E", 1, load::ld_d_e),
    Instruction::new("LD D,H", 1, load::ld_d_h),
    Instruction::new("LD D,L", 1, load::ld_d_l),
    Instruction::new("LD D,(HL)", 1, load::ld_d_hl_addr),
    Instruction::new("LD D,A", 1, load::ld_d_a),
    Instruction::new("LD E,B", 1, load::ld_e_b),
    Instruction::new("LD E,C", 1, load::ld_e_c),
    Instruction::new("LD E,D", 1, load::ld_e_d),
    Instruction::new("LD E,E", 1, load::ld_e_e),
    Instruction::new("LD E,H", 1, load::ld_e_h),
    Instruction::new("LD E,L", 1, load::ld_e_l),
    Instruction::new("LD E,(HL)", 1, load::ld_e_hl_addr),
    Instruction::new("LD E,A", 1, load::ld_e_a),
    Instruction::new("LD H,B", 1, load::ld_h_b),
    Instruction::new("LD H,C", 1, load::ld_h_c),
    Instruction::new("LD H,D", 1, load::ld_h_d),
    Instruction::new("LD H,E", 1, load::ld_h_e),
    Instruction::new("LD H,H", 1, load::ld_h_h),
    Instruction::new("LD H,L", 1, load::ld_h_l),
    Instruction::new("LD H,(HL)", 1, load::ld_h_hl_addr),
    Instruction::new("LD H,A", 1, load::ld_h_a),
    Instruction::new("LD L,B", 1, load::ld_l_b),
    Instruction::new("LD L,C", 1, load::ld_l_c),
    Instruction::new("LD L,D", 1, load::ld_l_d),
    Instruction::new("LD L,E", 1, load::ld_l_e),
    Instruction::new("LD L,H", 1, load::ld_l_h),
    Instruction::new("LD L,L", 1, load::ld_l_l),
    Instruction::new("LD L,(HL)", 1, load::ld_l_hl_addr),
    Instruction::new("LD L,A", 1, load::ld_l_a),
    Instruction::new("LD (HL),B", 1, load::ld_hl_addr_b),
    Instruction::new("LD (HL),C", 1, load::ld_hl_addr_c),
    Instruction::new("LD (HL),D", 1, load::ld_hl_addr_d),
    Instruction::new("LD (HL),E", 1, load::ld_hl_addr_e),
    Instruction::new("LD (HL),H", 1, load::ld_hl_addr_h),
    Instruction::new("LD (HL),L", 1, load::ld_hl_addr_l),
    Instruction::new("HALT", 1, misc::halt),
    Instruction::new("LD (HL),A", 1, load::ld_hl_addr_a),
    Instruction::new("LD A,B", 1, load::ld_a_b),
    Instruction::new("LD A,C", 1, load::ld_a_c),
    Instruction::new("LD A,D", 1, load::ld_a_d),
    Instruction::new("LD A,E", 1, load::ld_a_e),
    Instruction::new("LD A,H", 1, load::ld_a_h),
    Instruction::new("LD A,L", 1, load::ld_a_l),
    Instruction::new("LD A,(HL)", 1, load::ld_a_hl_addr),
    Instruction::new("LD A,A", 1, load::ld_a_a),
    Instruction::new("ADD A,B", 1, arithmetic::add_a_b),
    Instruction::new("ADD A,C", 1, arithmetic::add_a_c),
    Instruction::new("ADD A,D", 1, arithmetic::add_a_d),
    Instruction::new("ADD A,E", 1, arithmetic::add_a_e),
    Instruction::new("ADD A,H", 1, arithmetic::add_a_h),
    Instruction::new("ADD A,L", 1, arithmetic::add_a_l),
    Instruction::new("ADD A,(HL)", 1, arithmetic::add_a_hl_addr),
    Instruction::new("ADD A,A", 1, arithmetic::add_a_a),
    Instruction::new("ADC A,B", 1, arithmetic::adc_a_b),
    Instruction::new("ADC A,C", 1, arithmetic::adc_a_c),
    Instruction::new("ADC A,D", 1, arithmetic::adc_a_d),
    Instruction::new("ADC A,E", 1, arithmetic::adc_a_e),
    Instruction::new("ADC A,H", 1, arithmetic::adc_a_h),
    Instruction::new("ADC A,L", 1, arithmetic::adc_a_l),
    Instruction::new("ADC A,(HL)", 1, arithmetic::adc_a_hl_addr),
    Instruction::new("ADC A,A", 1, arithmetic::adc_a_a),
    Instruction::new("SUB B", 1, arithmetic::sub_b),
    Instruction::new("SUB C", 1, arithmetic::sub_c),
    Instruction::new("SUB D", 1, arithmetic::sub_d),
    Instruction::new("SUB E", 1, arithmetic::sub_e),
    Instruction::new("SUB H", 1, arithmetic::sub_h),
    Instruction::new("SUB L", 1, arithmetic::sub_l),
    Instruction::new("SUB (HL)", 1, arithmetic::sub_hl_addr),
    Instruction::new("SUB A", 1, arithmetic::sub_a),
    Instruction::new("SBC A,B", 1, arithmetic::sbc_a_b),
    Instruction::new("SBC A,C", 1, arithmetic::sbc_a_c),
    Instruction::new("SBC A,D", 1, arithmetic::sbc_a_d),
    Instruction::new("SBC A,E", 1, arithmetic::sbc_a_e),
    Instruction::new("SBC A,H", 1, arithmetic::sbc_a_h),
    Instruction::new("SBC A,L", 1, arithmetic::sbc_a_l),
    Instruction::new("SBC A,(HL)", 1, arithmetic::sbc_a_hl_addr),
    Instruction::new("SBC A,A", 1, arithmetic::sbc_a_a),
    Instruction::new("AND B", 1, arithmetic::and_b),
    Instruction::new("AND C", 1, arithmetic::and_c),
    Instruction::new("AND D", 1, arithmetic::and_d),
    Instruction::new("AND E", 1, arithmetic::and_e),
    Instruction::new("AND H", 1, arithmetic::and_h),
    Instruction::new("AND L", 1, arithmetic::and_l),
    Instruction::new("AND (HL)", 1, arithmetic::and_hl_addr),
    Instruction::new("AND A", 1, arithmetic::and_a),
    Instruction::new("XOR B", 1, arithmetic::xor_b),
    Instruction::new("XOR C", 1, arithmetic::xor_c),
    Instruction::new("XOR D", 1, arithmetic::xor_d),
    Instruction::new("XOR E", 1, arithmetic::xor_e),
    Instruction::new("XOR H", 1, arithmetic::xor_h),
    Instruction::new("XOR L", 1, arithmetic::xor_l),
    Instruction::new("XOR (HL)", 1, arithmetic::xor_hl_addr),
    Instruction::new("XOR A", 1, arithmetic::xor_a),
    Instruction::new("OR B", 1, arithmetic::or_b),
    Instruction::new("OR C", 1, arithmetic::or_c),
    Instruction::new("OR D", 1, arithmetic::or_d),
    Instruction::new("OR E", 1, arithmetic::or_e),
    Instruction::new("OR H", 1, arithmetic::or_h),
    Instruction::new("OR L", 1, arithmetic::or_l),
    Instruction::new("OR (HL)", 1, arithmetic::or_hl_addr),
    Instruction::new("OR A", 1, arithmetic::or_a),
    Instruction::new("CP B", 1, arithmetic::cp_b),
    Instruction::new("CP C", 1, arithmetic::cp_c),
    Instruction::new("CP D", 1, arithmetic::cp_d),
    Instruction::new("CP E", 1, arithmetic::cp_e),
    Instruction::new("CP H", 1, arithmetic::cp_h),
    Instruction::new("CP L", 1, arithmetic::cp_l),
    Instruction::new("CP (HL)", 1, arithmetic::cp_hl_addr),
    Instruction::new("CP A", 1, arithmetic::cp_a),
    Instruction::new("RET NZ", 1, jump::ret_nz),
    Instruction::new("POP BC", 1, load::pop_bc),
    Instruction::new("JP NZ,a16", 3, jump::jp_nz_a16),
    Instruction::new("JP a16", 3, jump::jp_a16),
    Instruction::new("CALL NZ,a16", 3, jump::call_nz_a16),
    Instruction::new("PUSH BC", 1, load::push_bc),
    Instruction::new("ADD A,d8", 2, arithmetic::add_a_d8),
    Instruction::new("RST 00H", 1, jump::rst_00h),
    Instruction::new("RET Z", 1, jump::ret_z),
    Instruction::new("RET", 1, jump::ret),
    Instruction::new("JP Z,a16", 3, jump::jp_z_a16),
    Instruction::new("PREFIX CB", 1, misc::prefix_cb),
    Instruction::new("CALL Z,a16", 3, jump::call_z_a16),
    Instruction::new("CALL a16", 3, jump::call_a16),
    Instruction::new("ADC A,d8", 2, arithmetic::adc_a_d8),
    Instruction::new("RST 08H", 1, jump::rst_08h),
    Instruction::new("RET NC", 1, jump::ret_nc),
    Instruction::new("POP DE", 1, load::pop_de),
    Instruction::new("JP NC,a16", 3, jump::jp_nc_a16),
    UNDEFINED,
    Instruction::new("CALL NC,a16", 3, jump::call_nc_a16),
    Instruction::new("PUSH DE", 1, load::push_de),
    Instruction::new("SUB d8", 2, arithmetic::sub_d8),
    Instruction::new("RST 10H", 1, jump::rst_10h),
    Instruction::new("RET C", 1, jump::ret_c),
    Instruction::new("RETI", 1, jump::reti),
    Instruction::new("JP C,a16", 3, jump::jp_c_a16),
    UNDEFINED,
    Instruction::new("CALL C,a16", 3, jump::call_c_a16),
    UNDEFINED,
    Instruction::new("SBC A,d8", 2, arithmetic::sbc_a_d8),
    Instruction::new("RST 18H", 1, jump::rst_18h),
    Instruction::new("LDH (a8),A", 2, load::ldh_a8_addr_a),
    Instruction::new("POP HL", 1, load::pop_hl),
    Instruction::new("LD (C),A", 1, load::ld_c_addr_a),
    UNDEFINED,
    UNDEFINED,
    Instruction::new("PUSH HL", 1, load::push_hl),
    Instruction::new("AND d8", 2, arithmetic::and_d8),
    Instruction::new("RST 20H", 1, jump::rst_20h),
    Instruction::new("ADD SP,r8", 2, arithmetic::add_sp_r8),
    Instruction::new("JP (HL)", 1, jump::jp_hl_addr),
    Instruction::new("LD (a16),A", 3, load::ld_a16_addr_a),
    UNDEFINED,
    UNDEFINED,
    UNDEFINED,
    Instruction::new("XOR d8", 2, arithmetic::xor_d8),
    Instruction::new("RST 28H", 1, jump::rst_28h),
    Instruction::new("LDH A,(a8)", 2, load::ldh_a_a8_addr),
    Instruction::new("POP AF", 1, load::pop_af),
    Instruction::new("LD A,(C)", 1, load::ld_a_c_addr),
    Instruction::new("DI", 1, misc::di),
    UNDEFINED,
    Instruction::new("PUSH AF", 1, load::push_af),
    Instruction::new("OR d8", 2, arithmetic::or_d8),
    Instruction::new("RST 30H", 1, jump::rst_30h),
    Instruction::new("LD HL,SP+r8", 2, load::ld_hl_sp_plusr8),
    Instruction::new("LD SP,HL", 1, load::ld_sp_hl),
    Instruction::new("LD A,(a16)", 3, load::ld_a_a16_addr),
    Instruction::new("EI", 1, misc::ei),
    UNDEFINED,
    UNDEFINED,
    Instruction::new("CP d8", 2, arithmetic::cp_d8),
    Instruction::new("RST 38H", 1, jump::rst_38h),
];

pub const PREFIX_CB_INSTRUCTIONS: [Instruction; 0x100] = [
    Instruction::new("RLC B", 2, bit::rlc_b),
    Instruction::new("RLC C", 2, bit::rlc_c),
    Instruction::new("RLC D", 2, bit::rlc_d),
    Instruction::new("RLC E", 2, bit::rlc_e),
    Instruction::new("RLC H", 2, bit::rlc_h),
    Instruction::new("RLC L", 2, bit::rlc_l),
    Instruction::new("RLC (HL)", 2, bit::rlc_hl_addr),
    Instruction::new("RLC A", 2, bit::rlc_a),
    Instruction::new("RRC B", 2, bit::rrc_b),
    Instruction::new("RRC C", 2, bit::rrc_c),
    Instruction::new("RRC D", 2, bit::rrc_d),
    Instruction::new("RRC E", 2, bit::rrc_e),
    Instruction::new("RRC H", 2, bit::rrc_h),
    Instruction::new("RRC L", 2, bit::rrc_l),
    Instruction::new("RRC (HL)", 2, bit::rrc_hl_addr),
    Instruction::new("RRC A", 2, bit::rrc_a),
    Instruction::new("RL B", 2, bit::rl_b),
    Instruction::new("RL C", 2, bit::rl_c),
    Instruction::new("RL D", 2, bit::rl_d),
    Instruction::new("RL E", 2, bit::rl_e),
    Instruction::new("RL H", 2, bit::rl_h),
    Instruction::new("RL L", 2, bit::rl_l),
    Instruction::new("RL (HL)", 2, bit::rl_hl_addr),
    Instruction::new("RL A", 2, bit::rl_a),
    Instruction::new("RR B", 2, bit::rr_b),
    Instruction::new("RR C", 2, bit::rr_c),
    Instruction::new("RR D", 2, bit::rr_d),
    Instruction::new("RR E", 2, bit::rr_e),
    Instruction::new("RR H", 2, bit::rr_h),
    Instruction::new("RR L", 2, bit::rr_l),
    Instruction::new("RR (HL)", 2, bit::rr_hl_addr),
    Instruction::new("RR A", 2, bit::rr_a),
    Instruction::new("SLA B", 2, bit::sla_b),
    Instruction::new("SLA C", 2, bit::sla_c),
    Instruction::new("SLA D", 2, bit::sla_d),
    Instruction::new("SLA E", 2, bit::sla_e),
    Instruction::new("SLA H", 2, bit::sla_h),
    Instruction::new("SLA L", 2, bit::sla_l),
    Instruction::new("SLA (HL)", 2, bit::sla_hl_addr),
    Instruction::new("SLA A", 2, bit::sla_a),
    Instruction::new("SRA B", 2, bit::sra_b),
    Instruction::new("SRA C", 2, bit::sra_c),
    Instruction::new("SRA D", 2, bit::sra_d),
    Instruction::new("SRA E", 2, bit::sra_e),
    Instruction::new("SRA H", 2, bit::sra_h),
    Instruction::new("SRA L", 2, bit::sra_l),
    Instruction::new("SRA (HL)", 2, bit::sra_hl_addr),
    Instruction::new("SRA A", 2, bit::sra_a),
    Instruction::new("SWAP B", 2, bit::swap_b),
    Instruction::new("SWAP C", 2, bit::swap_c),
    Instruction::new("SWAP D", 2, bit::swap_d),
    Instruction::new("SWAP E", 2, bit::swap_e),
    Instruction::new("SWAP H", 2, bit::swap_h),
    Instruction::new("SWAP L", 2, bit::swap_l),
    Instruction::new("SWAP (HL)", 2, bit::swap_hl_addr),
    Instruction::new("SWAP A", 2, bit::swap_a),
    Instruction::new("SRL B", 2, bit::srl_b),
    Instruction::new("SRL C", 2, bit::srl_c),
    Instruction::new("SRL D", 2, bit::srl_d),
    Instruction::new("SRL E", 2, bit::srl_e),
    Instruction::new("SRL H", 2, bit::srl_h),
    Instruction::new("SRL L", 2, bit::srl_l),
    Instruction::new("SRL (HL)", 2, bit::srl_hl_addr),
    Instruction::new("SRL A", 2, bit::srl_a),
    Instruction::new("BIT 0,B", 2, bit::bit_0_b),
    Instruction::new("BIT 0,C", 2, bit::bit_0_c),
    Instruction::new("BIT 0,D", 2, bit::bit_0_d),
    Instruction::new("BIT 0,E", 2, bit::bit_0_e),
    Instruction::new("BIT 0,H", 2, bit::bit_0_h),
    Instruction::new("BIT 0,L", 2, bit::bit_0_l),
    Instruction::new("BIT 0,(HL)", 2, bit::bit_0_hl_addr),
    Instruction::new("BIT 0,A", 2, bit::bit_0_a),
    Instruction::new("BIT 1,B", 2, bit::bit_1_b),
    Instruction::new("BIT 1,C", 2, bit::bit_1_c),
    Instruction::new("BIT 1,D", 2, bit::bit_1_d),
    Instruction::new("BIT 1,E", 2, bit::bit_1_e),
    Instruction::new("BIT 1,H", 2, bit::bit_1_h),
    Instruction::new("BIT 1,L", 2, bit::bit_1_l),
    Instruction::new("BIT 1,(HL)", 2, bit::bit_1_hl_addr),
    Instruction::new("BIT 1,A", 2, bit::bit_1_a),
    Instruction::new("BIT 2,B", 2, bit::bit_2_b),
    Instruction::new("BIT 2,C", 2, bit::bit_2_c),
    Instruction::new("BIT 2,D", 2, bit::bit_2_d),
    Instruction::new("BIT 2,E", 2, bit::bit_2_e),
    Instruction::new("BIT 2,H", 2, bit::bit_2_h),
    Instruction::new("BIT 2,L", 2, bit::bit_2_l),
    Instruction::new("BIT 2,(HL)", 2, bit::bit_2_hl_addr),
    Instruction::new("BIT 2,A", 2, bit::bit_2_a),
    Instruction::new("BIT 3,B", 2, bit::bit_3_b),
    Instruction::new("BIT 3,C", 2, bit::bit_3_c),
    Instruction::new("BIT 3,D", 2, bit::bit_3_d),
    Instruction::new("BIT 3,E", 2, bit::bit_3_e),
    Instruction::new("BIT 3,H", 2, bit::bit_3_h),
    Instruction::new("BIT 3,L", 2, bit::bit_3_l),
    Instruction::new("BIT 3,(HL)", 2, bit::bit_3_hl_addr),
    Instruction::new("BIT 3,A", 2, bit::bit_3_a),
    Instruction::new("BIT 4,B", 2, bit::bit_4_b),
    Instruction::new("BIT 4,C", 2, bit::bit_4_c),
    Instruction::new("BIT 4,D", 2, bit::bit_4_d),
    Instruction::new("BIT 4,E", 2, bit::bit_4_e),
    Instruction::new("BIT 4,H", 2, bit::bit_4_h),
    Instruction::new("BIT 4,L", 2, bit::bit_4_l),
    Instruction::new("BIT 4,(HL)", 2, bit::bit_4_hl_addr),
    Instruction::new("BIT 4,A", 2, bit::bit_4_a),
    Instruction::new("BIT 5,B", 2, bit::bit_5_b),
    Instruction::new("BIT 5,C", 2, bit::bit_5_c),
    Instruction::new("BIT 5,D", 2, bit::bit_5_d),
    Instruction::new("BIT 5,E", 2, bit::bit_5_e),
    Instruction::new("BIT 5,H", 2, bit::bit_5_h),
    Instruction::new("BIT 5,L", 2, bit::bit_5_l),
    Instruction::new("BIT 5,(HL)", 2, bit::bit_5_hl_addr),
    Instruction::new("BIT 5,A", 2, bit::bit_5_a),
    Instruction::new("BIT 6,B", 2, bit::bit_6_b),
    Instruction::new("BIT 6,C", 2, bit::bit_6_c),
    Instruction::new("BIT 6,D", 2, bit::bit_6_d),
    Instruction::new("BIT 6,E", 2, bit::bit_6_e),
    Instruction::new("BIT 6,H", 2, bit::bit_6_h),
    Instruction::new("BIT 6,L", 2, bit::bit_6_l),
    Instruction::new("BIT 6,(HL)", 2, bit::bit_6_hl_addr),
    Instruction::new("BIT 6,A", 2, bit::bit_6_a),
    Instruction::new("BIT 7,B", 2, bit::bit_7_b),
    Instruction::new("BIT 7,C", 2, bit::bit_7_c),
    Instruction::new("BIT 7,D", 2, bit::bit_7_d),
    Instruction::new("BIT 7,E", 2, bit::bit_7_e),
    Instruction::new("BIT 7,H", 2, bit::bit_7_h),
    Instruction::new("BIT 7,L", 2, bit::bit_7_l),
    Instruction::new("BIT 7,(HL)", 2, bit::bit_7_hl_addr),
    Instruction::new("BIT 7,A", 2, bit::bit_7_a),
    Instruction::new("RES 0,B", 2, bit::res_0_b),
    Instruction::new("RES 0,C", 2, bit::res_0_c),
    Instruction::new("RES 0,D", 2, bit::res_0_d),
    Instruction::new("RES 0,E", 2, bit::res_0_e),
    Instruction::new("RES 0,H", 2, bit::res_0_h),
    Instruction::new("RES 0,L", 2, bit::res_0_l),
    Instruction::new("RES 0,(HL)", 2, bit::res_0_hl_addr),
    Instruction::new("RES 0,A", 2, bit::res_0_a),
    Instruction::new("RES 1,B", 2, bit::res_1_b),
    Instruction::new("RES 1,C", 2, bit::res_1_c),
    Instruction::new("RES 1,D", 2, bit::res_1_d),
    Instruction::new("RES 1,E", 2, bit::res_1_e),
    Instruction::new("RES 1,H", 2, bit::res_1_h),
    Instruction::new("RES 1,L", 2, bit::res_1_l),
    Instruction::new("RES 1,(HL)", 2, bit::res_1_hl_addr),
    Instruction::new("RES 1,A", 2, bit::res_1_a),
    Instruction::new("RES 2,B", 2, bit::res_2_b),
    Instruction::new("RES 2,C", 2, bit::res_2_c),
    Instruction::new("RES 2,D", 2, bit::res_2_d),
    Instruction::new("RES 2,E", 2, bit::res_2_e),
    Instruction::new("RES 2,H", 2, bit::res_2_h),
    Instruction::new("RES 2,L", 2, bit::res_2_l),
    Instruction::new("RES 2,(HL)", 2, bit::res_2_hl_addr),
    Instruction::new("RES 2,A", 2, bit::res_2_a),
    Instruction::new("RES 3,B", 2, bit::res_3_b),
    Instruction::new("RES 3,C", 2, bit::res_3_c),
    Instruction::new("RES 3,D", 2, bit::res_3_d),
    Instruction::new("RES 3,E", 2, bit::res_3_e),
    Instruction::new("RES 3,H", 2, bit::res_3_h),
    Instruction::new("RES 3,L", 2, bit::res_3_l),
    Instruction::new("RES 3,(HL)", 2, bit::res_3_hl_addr),
    Instruction::new("RES 3,A", 2, bit::res_3_a),
    Instruction::new("RES 4,B", 2, bit::res_4_b),
    Instruction::new("RES 4,C", 2, bit::res_4_c),
    Instruction::new("RES 4,D", 2, bit::res_4_d),
    Instruction::new("RES 4,E", 2, bit::res_4_e),
    Instruction::new("RES 4,H", 2, bit::res_4_h),
    Instruction::new("RES 4,L", 2, bit::res_4_l),
    Instruction::new("RES 4,(HL)", 2, bit::res_4_hl_addr),
    Instruction::new("RES 4,A", 2, bit::res_4_a),
    Instruction::new("RES 5,B", 2, bit::res_5_b),
    Instruction::new("RES 5,C", 2, bit::res_5_c),
    Instruction::new("RES 5,D", 2, bit::res_5_d),
    Instruction::new("RES 5,E", 2, bit::res_5_e),
    Instruction::new("RES 5,H", 2, bit::res_5_h),
    Instruction::new("RES 5,L", 2, bit::res_5_l),
    Instruction::new("RES 5,(HL)", 2, bit::res_5_hl_addr),
    Instruction::new("RES 5,A", 2, bit::res_5_a),
    Instruction::new("RES 6,B", 2, bit::res_6_b),
    Instruction::new("RES 6,C", 2, bit::res_6_c),
    Instruction::new("RES 6,D", 2, bit::res_6_d),
    Instruction::new("RES 6,E", 2, bit::res_6_e),
    Instruction::new("RES 6,H", 2, bit::res_6_h),
    Instruction::new("RES 6,L", 2, bit::res_6_l),
    Instruction::new("RES 6,(HL)", 2, bit::res_6_hl_addr),
    Instruction::new("RES 6,A", 2, bit::res_6_a),
    Instruction::new("RES 7,B", 2, bit::res_7_b),
    Instruction::new("RES 7,C", 2, bit::res_7_c),
    Instruction::new("RES 7,D", 2, bit::res_7_d),
    Instruction::new("RES 7,E", 2, bit::res_7_e),
    Instruction::new("RES 7,H", 2, bit::res_7_h),
    Instruction::new("RES 7,L", 2, bit::res_7_l),
    Instruction::new("RES 7,(HL)", 2, bit::res_7_hl_addr),
    Instruction::new("RES 7,A", 2, bit::res_7_a),
    Instruction::new("SET 0,B", 2, bit::set_0_b),
    Instruction::new("SET 0,C", 2, bit::set_0_c),
    Instruction::new("SET 0,D", 2, bit::set_0_d),
    Instruction::new("SET 0,E", 2, bit::set_0_e),
    Instruction::new("SET 0,H", 2, bit::set_0_h),
    Instruction::new("SET 0,L", 2, bit::set_0_l),
    Instruction::new("SET 0,(HL)", 2, bit::set_0_hl_addr),
    Instruction::new("SET 0,A", 2, bit::set_0_a),
    Instruction::new("SET 1,B", 2, bit::set_1_b),
    Instruction::new("SET 1,C", 2, bit::set_1_c),
    Instruction::new("SET 1,D", 2, bit::set_1_d),
    Instruction::new("SET 1,E", 2, bit::set_1_e),
    Instruction::new("SET 1,H", 2, bit::set_1_h),
    Instruction::new("SET 1,L", 2, bit::set_1_l),
    Instruction::new("SET 1,(HL)", 2, bit::set_1_hl_addr),
    Instruction::new("SET 1,A", 2, bit::set_1_a),
    Instruction::new("SET 2,B", 2, bit::set_2_b),
    Instruction::new("SET 2,C", 2, bit::set_2_c),
    Instruction::new("SET 2,D", 2, bit::set_2_d),
    Instruction::new("SET 2,E", 2, bit::set_2_e),
    Instruction::new("SET 2,H", 2, bit::set_2_h),
    Instruction::new("SET 2,L", 2, bit::set_2_l),
    Instruction::new("SET 2,(HL)", 2, bit::set_2_hl_addr),
    Instruction::new("SET 2,A", 2, bit::set_2_a),
    Instruction::new("SET 3,B", 2, bit::set_3_b),
    Instruction::new("SET 3,C", 2, bit::set_3_c),
    Instruction::new("SET 3,D", 2, bit::set_3_d),
    Instruction::new("SET 3,E", 2, bit::set_3_e),
    Instruction::new("SET 3,H", 2, bit::set_3_h),
    Instruction::new("SET 3,L", 2, bit::set_3_l),
    Instruction::new("SET 3,(HL)", 2, bit::set_3_hl_addr),
    Instruction::new("SET 3,A", 2, bit::set_3_a),
    Instruction::new("SET 4,B", 2, bit::set_4_b),
    Instruction::new("SET 4,C", 2, bit::set_4_c),
    Instruction::new("SET 4,D", 2, bit::set_4_d),
    Instruction::new("SET 4,E", 2, bit::set_4_e),
    Instruction::new("SET 4,H", 2, bit::set_4_h),
    Instruction::new("SET 4,L", 2, bit::set_4_l),
    Instruction::new("SET 4,(HL)", 2, bit::set_4_hl_addr),
    Instruction::new("SET 4,A", 2, bit::set_4_a),
    Instruction::new("SET 5,B", 2, bit::set_5_b),
    Instruction::new("SET 5,C", 2, bit::set_5_c),
    Instruction::new("SET 5,D", 2, bit::set_5_d),
    Instruction::new("SET 5,E", 2, bit::set_5_e),
    Instruction::new("SET 5,H", 2, bit::set_5_h),
    Instruction::new("SET 5,L", 2, bit::set_5_l),
    Instruction::new("SET 5,(HL)", 2, bit::set_5_hl_addr),
    Instruction::new("SET 5,A", 2, bit::set_5_a),
    Instruction::new("SET 6,B", 2, bit::set_6_b),
    Instruction::new("SET 6,C", 2, bit::set_6_c),
    Instruction::new("SET 6,D", 2, bit::set_6_d),
    Instruction::new("SET 6,E", 2, bit::set_6_e),
    Instruction::new("SET 6,H", 2, bit::set_6_h),
    Instruction::new("SET 6,L", 2, bit::set_6_l),
    Instruction::new("SET 6,(HL)", 2, bit::set_6_hl_addr),
    Instruction::new("SET 6,A", 2, bit::set_6_a),
    Instruction::new("SET 7,B", 2, bit::set_7_b),
    Instruction::new("SET 7,C", 2, bit::set_7_c),
    Instruction::new("SET 7,D", 2, bit::set_7_d),
    Instruction::new("SET 7,E", 2, bit::set_7_e),
    Instruction::new("SET 7,H", 2, bit::set_7_h),
    Instruction::new("SET 7,L", 2, bit::set_7_l),
    Instruction::new("SET 7,(HL)", 2, bit::set_7_hl_addr),
    Instruction::new("SET 7,A", 2, bit::set_7_a),
];
